### ISSUE TITLE
Version on about screen is still 0.1.7 in v 0.1.8

### ISSUE THREAD

**Issue by zob** [Nokse22/inspector#23]
Hi.
Minor detail, but I stumbled upon this because version 0.1.7 installed from snap doesn't show any output in any of the views on ubuntu 24.04. Updating to 0.1.8 from the edge channel solved this issue.

However I was a little confused about which version I was running, because the version number on the about screen wasn't updated - maybe you can take it from somewhere else so you don't have to update in two places every time ;)
https://github.com/Nokse22/inspector/blob/85aaf0e0ee7086238b225235c0f85b896433933c/src/main.py#L74

But nice tool!

**Comment by Nokse22** [comment]
Thank you, I have released a new version, unfortunately there is nothing to do to fix the old one. It would be very useful to just have to update the version once.

BTW you will not be able to use it for some time if you use snaps, because canonical won't update the runtime.
