### ISSUE TITLE
Suggestion<

### ISSUE THREAD

**Issue by zaheermk1** [Nokse22/inspector#8]
Hi,

First of all, since I like using the GUI more than the CLI, I like the Inspector application.
And more so, since you have given the command used, I love the Inspector application.

Since I get to see the command used, I feel it would be great if it was in 'uniform'/'systematic'.

When I check, I have the following ls based commands in my system...
lscpu
lsmem
lsblk
lspci
lsusb

So, if possible, can you please set them in the below order?
sys/devices/virtual/dmi/id -> motherboard
lscpu   -> processor
lsmem -> memory
lsblk    -> disk drives
lspci    -> pci devices
lsusb   -> usb devices
ip address -> network devices
uname -a -> kernel
cat /etc/os-release -> distribution

Distro is a 'casual usage' kind of word. Distribution is the proper word for it.

And I feel it was a brilliant idea to capture the details from /sys/devices/virtual/dmi/id and display it (it was a new info for me.)

I will try to update/suggest new commands when/if I come to know.

Thanking you very much/once more for the Inspector application.

**Comment by Nokse22** [comment]
Hello, thank you so much!
I will surely follow your advices in the next version of this application that will also feature a design overhaul. (https://github.com/Nokse22/inspector/issues/3#issuecomment-1679177761)
The titles you suggested are of similar length and should look even better.

I agree it was a brilliant idea to capture the details from /sys/devices/virtual/dmi/id, it was not my idea. https://github.com/Nokse22/inspector/pull/2
